### ISSUE TITLE
RF switches

### ISSUE THREAD

**Issue by sporkchops81** [sporkchops81/home-assistant-config#1]
Use Etekcity rf switches with 433mhz receiver/transmitter on pi

Need to figure out how to physically add and then configure

**Comment by sporkchops81** [comment]
Need rpi_rf python package

```yaml
# Example configuration.yaml entry
switch:
  platform: rpi_rf
  gpio: 17
  switches:
    bedroom_light:
      code_on: 1234567
      code_off: 1234568
    ambilight:
      pulselength: 200
      code_on: 987654
      code_off: 133742
    living_room_light:
      protocol: 5
      code_on: 654321,565874,233555,149874
      code_off: 654320,565873,233554,149873
      signal_repetitions: 15
```
