### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by sporkchops81** [sporkchops81/home-assistant-config#10]
# User to send messages with Automation
```yaml
# Sample automation notification
automation:
  - alias: Check sensor value and show notification
    trigger:
      platform: numeric_state
      entity_id: sensor.random_sensor
      above: 10
    action:
      service: persistent_notification.create
      data:
        message: "Sensor value greater than 10"
```
# FireTV
Download [FireTV Notifier](https://play.google.com/store/apps/details?id=de.cyberdream.firenotifications.google)
Then,
```yaml
# Example configuration.yaml entry
notify:
- platform: nfandroidtv
  name: Kitchen
  host: 192.168.1.12
  duration: 5
  position: bottom-left
```
# SimplePush
To test if the service works, just send a message with curl from the command-line.

`$ curl 'https://api.simplepush.io/send/device_key/title/message'`

```yaml
# Example configuration.yaml entry
notify:
  - name: NOTIFIER_NAME
    platform: simplepush
    device_key: ABCDE
```
