### ISSUE TITLE
Formatting configuration.yaml

### ISSUE THREAD

**Issue by sporkchops81** [sporkchops81/home-assistant-config#12]
# General
### Be sure to include `secrets.yaml` in `.gitignore`
To do so, replace 
```yaml
http:
  api_password: YOUR_PASSWORD
```
with this:
```yaml
http:
  api_password: !secret http_password
```
Then, in `secrets.yaml` place the secret info

`http_password: YOUR_PASSWORD`

### Alternatively, use Keyring:

`$ hass --script keyring --help`
Use the same method to replace the password in the config files, but instead of using secrets.yaml, instead use this:
`$ hass --script keyring set http_password`
## Core items left in configuration.yaml
```yaml
homeassistant:
  # Name of the location where Home Assistant is running
  name: My Home Assistant Instance
  # Location required to calculate the time the sun rises and sets
  latitude: 37
  longitude: -121
  altitude: 1
  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customize.yaml
  history:
  frontend:
  logbook:
  http:
    api_password: ImNotTelling!

  ifttt:
    key: [nope]

  wink:
    access_token: [wouldn't you]
    refresh_token: [like to know]

  zwave:
    usb_path: /dev/ttyUSB0
    config_path: /usr/local/share/python-openzwave/config
    polling_interval: 10000

  mqtt:
    broker: 127.0.0.1
```

# Splitting into files
To replace a section, use `!include [filename]`
```yaml
automation: !include automation.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
```
