### ISSUE TITLE
Thermostats

### ISSUE THREAD

**Issue by sporkchops81** [sporkchops81/home-assistant-config#13]
## Z-Wave Thermostat Automation
Add to `configuration.yaml':
```yaml
climate:
  platform: zwave
```
Then add an automation:
```yaml
# Note that there are two entities, one for mode and one for temp
# Also, can base automation off thermostat sensors (e.g., sensor.remotec_zxt120_temperature_38)
automation:
  - alias: Turn on Heater at 8pm
    trigger:
      - platform: time
        after: "20:00:00"
    action:
      - service: climate.set_operation_mode
        entity_id: climate.remotec_zxt120_heating_1_id
        data:
          operation_mode: Heat
      - service: climate.set_temperature
        entity_id: climate.remotec_zxt120_heating_1_39
        data:
          temperature: 24
```
