### ISSUE TITLE
Dark Sky

### ISSUE THREAD

**Issue by sporkchops81** [sporkchops81/home-assistant-config#5]
```yaml
# Example configuration.yaml entry
sensor:
  - platform: darksky
    api_key: YOUR_API_KEY
    latitude: ___
    longitude: ___
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
```
