### ISSUE TITLE
Presence Detection

### ISSUE THREAD

**Issue by sporkchops81** [sporkchops81/home-assistant-config#8]
# Device Trackers
## Ubiquiti AP
```yaml
    # Example configuration.yaml entry
    device_tracker:
      - platform: unifi
        username: YOUR_ADMIN_USERNAME
        password: YOUR_ADMIN_PASSWORD
```
## NMAP
```yaml
# Example configuration.yaml entry for nmap
# One whole subnet, and skipping two specific IPs.
device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.1/24
      - 10.0.0.2
      - 10.0.0.15
    home_interval: 10
    exclude:
     - 192.168.1.12
     - 192.168.1.13
```
