### ISSUE TITLE
Transmission Sensor

### ISSUE THREAD

**Issue by sporkchops81** [sporkchops81/home-assistant-config#9]
## Monitor status of downloads
Can react by sending notifications when downloads complete

```yaml
# Example configuration.yaml entry
sensor:
  - platform: transmission
    host: IP_ADDRESS
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
```
